# Generated by Django 4.0.6 on 2022-08-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=40, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('startdate', models.DateTimeField()),
            ],
        ),
    ]
