# Generated by Django 4.1 on 2022-08-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileupload",
            name="writer",
            field=models.CharField(default="", max_length=40),
        ),
    ]
