# Generated by Django 4.1 on 2022-08-04 02:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("file", "0002_fileupload_writer"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileupload",
            name="content",
            field=ckeditor.fields.RichTextField(default=""),
        ),
    ]
