# Generated by Django 4.0.6 on 2022-08-02 12:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0002_alter_manager_name_alter_member_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='teamname',
            new_name='team_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='team',
            name='member',
        ),
        migrations.AddField(
            model_name='team',
            name='managers',
            field=models.ManyToManyField(related_name='teams1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='manager',
        ),
        migrations.DeleteModel(
            name='member',
        ),
    ]
