# Generated by Django 4.0.6 on 2022-08-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
        ('team', '0003_remove_member_member_rename_teamname_team_team_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='task',
        ),
        migrations.AddField(
            model_name='team',
            name='task',
            field=models.ManyToManyField(related_name='task1', to='task.task'),
        ),
    ]
