# Generated by Django 4.0.6 on 2022-08-05 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, 'member'), (1, 'manager'), (2, 'creator')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=200, null=True)),
                ('region', models.IntegerField(choices=[(0, 'need to select'), (1, 'Frontend Team'), (2, 'Backend Team'), (3, 'Fullstack Team'), (4, 'Devops Team'), (5, 'Marketing Team')], default=0)),
                ('member', models.ManyToManyField(related_name='team', to='teamApp.member')),
            ],
        ),
    ]
