# Generated by Django 4.0.6 on 2022-08-05 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=200)),
                ('workerName', models.CharField(max_length=50)),
                ('start', models.DateTimeField(default=None, null=True)),
                ('ddl', models.DateTimeField(default=None, null=True)),
                ('status', models.IntegerField(choices=[(0, 'ready for worker'), (1, 'worker exists'), (2, 'on work'), (3, 'err found'), (4, 'completed'), (5, 'garbage')], default=0)),
                ('worker', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
