# Generated by Django 4.0.6 on 2022-08-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='group_name',
            field=models.CharField(default='task', max_length=200),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
